/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.rueggerllc.avro;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum Active {
  ROCK, PAPER, SCISSORS  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"Active\",\"namespace\":\"com.rueggerllc.avro\",\"symbols\":[\"ROCK\",\"PAPER\",\"SCISSORS\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
